### ISSUE TITLE
rooling realease base image

### ISSUE THREAD

**Issue by ayoubelmhamdi** [rhino-linux/rhino-setup#49]
Arch Void Gentoo linux, has a base image, without any desktop or xorgs ... and support iso and tar.gz

**Comment by ajstrongdev** [comment]
This repository is for the setup wizard for Rhino Linux, not the OS itself.

**Comment by ajstrongdev** [comment]
The correct place would be https://github.com/rhino-linux/os

At the moment we have no plans on supporting any other desktop environments officially, however we are working on a Server ISO which would act as a base image.

### Why do we ship Unicorn by default, and not provide other builds?

1. We have a specific vision for the desktop we want to push, and chose a base with the most foundations to provide a non-breaking experience on the devel branch.

2. Bug fixing every issue that occurs on every DE is way too much for our small dev team.

3. Packaging GNOME, KDE, etc to be compatible with our current customizations and core packaging, or creating alternative packaging for it, would be a pain.
