### ISSUE TITLE
BUG: Flatpak is not installed after reboot

### ISSUE THREAD

**Issue by markob94** [rhino-linux/rhino-setup#54]
**Rhino Linux Version:**
 `2023.1`

**Platform:**
AMD64

**Describe the bug**
After initial install, using rhino-setup and installing flatpak, , after install , flatpak is not installed 

**To Reproduce**
1. Go to 'rhino-setup'
2. Click install flatpak
3. Reboot
4. In terminal type  flatpak --version

**Expected behavior**
Version of flatpak is showed
![Screenshot_2023-08-21_20-30-09](https://github.com/rhino-linux/rhino-setup/assets/12753656/c3d70af6-162c-425c-8ad6-f9a4abd53e9c)

**Screenshots**
Attached

**Comment by ajstrongdev** [comment]
Thank you for your report. We will begin to look into this and attempt to resolve the issue.

**Comment by ajstrongdev** [comment]
I have assigned @cat-master21 to attempt to diagnose the issue. If we find an issue then we will work together to fix the issue.

**Comment by cat-master21** [comment]
So @ajstrongdev my findings are: by default, Flatpak is *not* installed despite it being on by default. In fact this issue also applies to Nala which is also enabled by default but not installed. The user has to reselect it.

**Comment by ajstrongdev** [comment]
@cat-master21 this issue never occurred originally.

**Comment by oklopfer** [comment]
> So @ajstrongdev my findings are: by default, Flatpak is _not_ installed despite it being on by default. In fact this issue also applies to Nala which is also enabled by default but not installed. The user has to reselect it.

Can you clarify what you mean about Nala? because the ISO has it installed by default, so not sure what you mean....
