### ISSUE TITLE
Feat: add Polkit authentication

### ISSUE THREAD

**Issue by cat-master21** [rhino-linux/rhino-setup#60]
So currently to reboot, `sudo`/root is needed and this can be eliminated by using Polkit. This is what Gnome Software uses I think. 
See https://wiki.archlinux.org/title/Polkit#Authorization_rules

**Comment by ajstrongdev** [comment]
@cat-master21 is there any update on this? If not I will be moving it into Rollover so that work can be started on it for 2023.4 instead.

**Comment by cat-master21** [comment]
@ajstrongdev you can rollover for this issue I did not have the time to look at it.
