### ISSUE TITLE
BUG: setup wizard tells me to contact the distribution developer

### ISSUE THREAD

**Issue by xyzaf1** [rhino-linux/rhino-setup#66]
**Rhino Linux Version:**
A numerical version for Rhino Linux. 
--> 2023.4 (latest at the moment of typing this)

**Platform:**
[x86_64 / i7 7700, 16gb RAM; iGPU]

**Describe the bug**
Video of the bug: [here](https://drive.proton.me/urls/7EDDQPQZRG#I52SgiKzOLnL)

** English translation of the error message:**
> 'something gone wrong, contact the distribution developer'

**To Reproduce**
1. Go to 'setup wizard'
2. Click on stuff shown in the video'
3. See error

**Expected behavior**
The setup wizard setting up things

**Screenshots**
[video](https://drive.proton.me/urls/7EDDQPQZRG#I52SgiKzOLnL)

**Additional context**
I hope it's not me beeing dumb or just missing something lol 

GitHub link to the video of my issue: https://github.com/rhino-linux/rhino-setup/assets/115548876/18c636d5-b10d-4517-8ce1-c3818f73918b

**Comment by ajstrongdev** [comment]
Interesting, are you able to run `rhino-system` in the command-line and when it fails paste the output?

**Comment by xyzaf1** [comment]
@ajstrongdev nope: `bash: rhino-system: command not found`

**Comment by xyzaf1** [comment]
@ajstrongdev @wizard-28 i'm getting the same error on a vmware 17 setup with a ryzen 7 4800h, 16gb ram. 

same with the rhino-system command:
```
$ rhino system
bash: rhino-system: command not found
```

**Comment by xyzaf1** [comment]
@ajstrongdev in case you meant "rhino-setup" instead of "rhino-system" this gave me the following output:
![image](https://github.com/rhino-linux/rhino-setup/assets/115548876/f7054853-8102-40cc-90a6-80e067456a90)
hope this helps

**Comment by D-Brox** [comment]
You were using an old version of pacstall, we recently had a breaking release back in the beginning of May. Running `pacstall -U` should fix it.

I already fixed it on my branch so this doesn't happen anymore, I'll be pushing it soon:
![image](https://github.com/rhino-linux/rhino-setup/assets/65723952/b452aad3-bdfe-4136-ae2c-ac56a10db5ac)

**Comment by D-Brox** [comment]
Permanently fixed in #68
