### ISSUE TITLE
BUG: setup wizard not showing up on primary monitor after initial upgrade and reboot.

### ISSUE THREAD

**Issue by iconoclasthero** [rhino-linux/rhino-setup#73]
**Rhino Linux Version:**
2024.01

**Platform:**
x86

**Describe the bug**
setup wizard not showing up on primary monitor after initial upgrade and reboot.

**To Reproduce**
setup wizard not showing up on primary monitor after initial upgrade and reboot.

**Expected behavior**
I expect that when I assign a primary monitor that this would appear on it.  

**Screenshots**
![setup wizard](https://github.com/user-attachments/assets/11ff00cf-fe05-4b3d-930e-acb4f927bcea)

**Additional context**

**Comment by D-Brox** [comment]
This is an issue with the way gtk determines the default display to be used, we have no control over this behavior on the rust side though the ffi.
